"""Remove QR columns

Revision ID: 258867365345
Revises: 37306e025b61
Create Date: 2026-09-19 20:13:42.284730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258867365345'
down_revision = '37306e025b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
