"""Batch 6 Schema Constraints

Revision ID: 37306e025b61
Revises: batch_4_schema_tightening
Create Date: 2026-09-09 18:51:24.267346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37306e025b61'
down_revision = 'batch_4_schema_tightening'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_check_constraint('chk_coupon_discount_amount', 'discount_amount >= 0')
        batch_op.create_check_constraint('chk_coupon_discount_pct', 'discount_pct >= 0 AND discount_pct <= 100')

    with op.batch_alter_table('kitchen_production_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('market_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_check_constraint('chk_menu_item_price', 'price >= 0')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_check_constraint('chk_order_item_qty', 'quantity > 0')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_check_constraint('chk_order_delivery_charge', 'delivery_charge >= 0')
        batch_op.create_check_constraint('chk_order_discount_amount', 'discount_amount >= 0')
        batch_op.create_check_constraint('chk_order_tax_amount', 'tax_amount >= 0')
        batch_op.create_check_constraint('chk_order_total_price', 'total_price >= 0')

    with op.batch_alter_table('outlet_stocks', schema=None) as batch_op:
        batch_op.create_check_constraint('chk_outlet_stock_current', 'current_stock >= 0')
        batch_op.create_check_constraint('chk_outlet_stock_limit', 'restock_limit >= 0')

    with op.batch_alter_table('supplier_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_check_constraint('chk_user_loyalty_points', 'loyalty_points >= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('chk_user_loyalty_points', type_='check')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_ibfk_2'), 'users', ['referred_by_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('supplier_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('outlet_stocks', schema=None) as batch_op:
        batch_op.drop_constraint('chk_outlet_stock_limit', type_='check')
        batch_op.drop_constraint('chk_outlet_stock_current', type_='check')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('chk_order_total_price', type_='check')
        batch_op.drop_constraint('chk_order_tax_amount', type_='check')
        batch_op.drop_constraint('chk_order_discount_amount', type_='check')
        batch_op.drop_constraint('chk_order_delivery_charge', type_='check')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('chk_order_item_qty', type_='check')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint('chk_menu_item_price', type_='check')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('market_purchases', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('kitchen_production_batches', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint('chk_coupon_discount_pct', type_='check')
        batch_op.drop_constraint('chk_coupon_discount_amount', type_='check')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
